# Generated by Django 3.2 on 2022-03-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=20)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
