# Generated by Django 3.2 on 2022-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.IntegerField(max_length=7, null=True),
        ),
    ]
