# Generated by Django 3.2 on 2022-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20220304_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.IntegerField(null=True),
        ),
    ]
